import React from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "./ui/button";
import Header from "./Header";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-900 via-indigo-900 to-purple-900">
      <Header />
      <div className="container mx-auto px-4 pt-24 pb-16">
        <div className="flex items-center mb-8">
          <Link to="/">
            <Button
              variant="ghost"
              size="sm"
              className="text-white hover:bg-white/10"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Button>
          </Link>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="bg-white/10 backdrop-blur-md rounded-xl border border-white/20 shadow-xl p-8"
        >
          <h1 className="text-3xl font-bold text-white mb-6">
            Terms of Service
          </h1>

          <div className="prose prose-invert max-w-none">
            <p className="text-gray-200">Last Updated: June 1, 2024</p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              1. Acceptance of Terms
            </h2>
            <p className="text-gray-200 mb-4">
              By accessing or using SoloLaunch ("the Service"), you agree to be
              bound by these Terms of Service. If you do not agree to these
              terms, please do not use the Service.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              2. Description of Service
            </h2>
            <p className="text-gray-200 mb-4">
              SoloLaunch provides tools for solo founders to generate startup
              ideas, names, pitches, and business plans using AI technology. The
              Service includes both free and premium features accessible through
              our website.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              3. User Accounts
            </h2>
            <p className="text-gray-200 mb-4">
              To access certain features of the Service, you must create an
              account. You are responsible for maintaining the confidentiality
              of your account credentials and for all activities that occur
              under your account. You agree to provide accurate and complete
              information when creating your account and to update your
              information as needed.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              4. Subscription and Payments
            </h2>
            <p className="text-gray-200 mb-4">
              SoloLaunch offers both free and premium subscription plans. By
              subscribing to a premium plan, you agree to pay the applicable
              fees as described at the time of purchase. Subscriptions
              automatically renew unless canceled before the renewal date. You
              can cancel your subscription at any time through your account
              settings.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              5. Intellectual Property
            </h2>
            <p className="text-gray-200 mb-4">
              The Service and its original content, features, and functionality
              are owned by SoloLaunch and are protected by international
              copyright, trademark, and other intellectual property laws. The
              content generated by our AI tools is owned by you once created,
              but we retain the right to use anonymized data to improve our
              services.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              6. User Content
            </h2>
            <p className="text-gray-200 mb-4">
              You retain ownership of any content you submit to the Service. By
              submitting content, you grant us a worldwide, non-exclusive,
              royalty-free license to use, reproduce, modify, and display your
              content for the purpose of operating and improving the Service.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              7. Prohibited Uses
            </h2>
            <p className="text-gray-200 mb-2">
              You agree not to use the Service to:
            </p>
            <ul className="list-disc pl-6 text-gray-200 mb-4">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon the rights of others</li>
              <li>Submit false or misleading information</li>
              <li>Upload or transmit viruses or malicious code</li>
              <li>Attempt to gain unauthorized access to the Service</li>
              <li>Use the Service for any illegal or unauthorized purpose</li>
            </ul>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              8. Limitation of Liability
            </h2>
            <p className="text-gray-200 mb-4">
              SoloLaunch shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages resulting from your
              use of or inability to use the Service. In no event shall our
              total liability exceed the amount you paid for the Service in the
              past 12 months.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              9. Termination
            </h2>
            <p className="text-gray-200 mb-4">
              We may terminate or suspend your account and access to the Service
              immediately, without prior notice, for conduct that we believe
              violates these Terms or is harmful to other users, us, or third
              parties, or for any other reason at our sole discretion.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              10. Changes to Terms
            </h2>
            <p className="text-gray-200 mb-4">
              We reserve the right to modify these Terms at any time. We will
              provide notice of significant changes by posting the new Terms on
              this page and updating the "Last Updated" date. Your continued use
              of the Service after such changes constitutes your acceptance of
              the new Terms.
            </p>

            <h2 className="text-xl font-semibold text-white mt-6 mb-3">
              11. Contact Us
            </h2>
            <p className="text-gray-200 mb-4">
              If you have any questions about these Terms, please contact us at
              terms@sololaunch.com.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default TermsOfService;
